"""fix salary_amount

Revision ID: 331e132652d8
Revises: 68667ba41e14
Create Date: 2025-06-07 15:31:43.478429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "331e132652d8"
down_revision: Union[str, None] = "68667ba41e14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vacancies",
        "salary_amount",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "vacancies", ["id"], schema="vnedreid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vacancies", schema="vnedreid", type_="unique")
    op.alter_column(
        "vacancies",
        "salary_amount",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
