"""fix radar table

Revision ID: 44935005ada2
Revises: bd34ae6dff98
Create Date: 2025-06-08 16:45:46.008093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44935005ada2'
down_revision: Union[str, None] = 'bd34ae6dff98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radar', sa.Column('vacancy_date', sa.Date(), nullable=True))
    op.add_column('radar', sa.Column('specialization', sa.Text(), nullable=True))
    op.add_column('radar', sa.Column('region', sa.Text(), nullable=True))
    op.add_column('radar', sa.Column('work_experience', sa.Text(), nullable=True))
    op.add_column('radar', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('radar', sa.Column('gender', sa.Text(), nullable=True))
    op.add_column('radar', sa.Column('salary_specified', sa.Boolean(), nullable=True))
    op.add_column('radar', sa.Column('salary_amount', sa.Float(), nullable=True))
    op.add_column('radar', sa.Column('company', sa.Text(), nullable=True))
    op.add_column('radar', sa.Column('vacancy_source', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'radar', ['id'], schema='vnedreid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'radar', schema='vnedreid', type_='unique')
    op.drop_column('radar', 'vacancy_source')
    op.drop_column('radar', 'company')
    op.drop_column('radar', 'salary_amount')
    op.drop_column('radar', 'salary_specified')
    op.drop_column('radar', 'gender')
    op.drop_column('radar', 'age')
    op.drop_column('radar', 'work_experience')
    op.drop_column('radar', 'region')
    op.drop_column('radar', 'specialization')
    op.drop_column('radar', 'vacancy_date')
    # ### end Alembic commands ###
