"""add resume table

Revision ID: 713e20c68063
Revises: 331e132652d8
Create Date: 2025-06-08 16:22:53.704471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713e20c68063'
down_revision: Union[str, None] = '331e132652d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('vacancy_date', sa.Date(), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('work_experience', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('salary_specified', sa.Boolean(), nullable=True),
    sa.Column('salary_amount', sa.Float(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('vacancy_source', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='vnedreid'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume', schema='vnedreid')
    # ### end Alembic commands ###
