"""add radar table

Revision ID: bd34ae6dff98
Revises: 713e20c68063
Create Date: 2025-06-08 16:44:28.033582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd34ae6dff98'
down_revision: Union[str, None] = '713e20c68063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar',
    sa.Column('medical_insurance', sa.Boolean(), nullable=True),
    sa.Column('meal', sa.Boolean(), nullable=True),
    sa.Column('gym', sa.Boolean(), nullable=True),
    sa.Column('flexible_schedule', sa.Boolean(), nullable=True),
    sa.Column('training', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='vnedreid'
    )
    op.create_unique_constraint(None, 'resume', ['id'], schema='vnedreid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume', schema='vnedreid', type_='unique')
    op.drop_table('radar', schema='vnedreid')
    # ### end Alembic commands ###
